[workspace]
resolver = "2"
members = [ "hanabi-bot", "hanabi-trainer", "hanabi-tui",
    "hanabi",
    "hanablive",
    "hanabi-web",
    # "hanabi-trainer",
    # "hanabi-tui",
    # "hanabi-bot",
]
